version: "3.9"

x-playwright-base: &playwright-base
  build:
    context: .
    dockerfile: docker/Dockerfile.playwright
  depends_on:
    juice-shop:
      condition: service_healthy
  env_file:
    - .env
  environment:
    BASE_URL: ${BASE_URL:-http://juice-shop:3000}
    HEADLESS: ${HEADLESS:-true}
  volumes:
    - ./:/app
    - playwright-node-modules:/app/node_modules
  user: "${PLAYWRIGHT_UID:-0}:${PLAYWRIGHT_GID:-0}"
  working_dir: /app

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    healthcheck:
      test:
        - CMD
        - /nodejs/bin/node
        - -e
        - "require('http').get('http://127.0.0.1:3000', res => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1));"
      interval: 10s
      timeout: 5s
      retries: 5

  playwright:
    <<: *playwright-base
    container_name: playwright-tests
    command: ["npx", "playwright", "test"]

  playwright-dev:
    <<: *playwright-base
    container_name: playwright-dev
    profiles:
      - dev
    command: ["sleep", "infinity"]
    stdin_open: true
    tty: true

volumes:
  playwright-node-modules: {}
